[font]
size = 16

[font.normal]
family = "JetbrainsMono Nerd Font Mono" 
style = "Regular"

[colors.normal]
black = "#2e2828"
red = "#a54242"
green = "#8c9440"
yellow = "#DE803F"
blue = "#256295"
magenta = "#85678f"
cyan = "#5e8d87"
white = "#807970"

[colors.bright]
black = "#423838"
red = "#cc6666"
green = "#b5bd68"
yellow = "#F0B94E"
blue = "#5185B1"
magenta = "#b294bb"
cyan = "#8abeb7"
white = "#c8c6c5"

[colors.primary]
foreground = "#f2a97d"
background = "#381818"

[general]
live_config_reload = true

